### ISSUE TITLE
Create UI Component Mockups

### ISSUE THREAD

**Issue by doug-stormtree** [CobeyH/SENG-480A#13]
For the meeting at 6:30pm Monday, Feb 6: Create and post low-fidelity UI mockups and component ideas here for discussion and adoption. Images less than 25MB can be added on this issue by dragging and dropping them onto the comment box.

**Comment by CobeyH** [comment]
![image](https://user-images.githubusercontent.com/32989729/152864001-3eafcfd0-4d5a-4344-9ce6-67848c4b5160.png)
![image](https://user-images.githubusercontent.com/32989729/152864050-a10eaab8-a14b-4246-a213-58f1674032f2.png)
![image](https://user-images.githubusercontent.com/32989729/152864081-c825b11c-c5e6-422c-8cf5-80fb7b8482af.png)
![image](https://user-images.githubusercontent.com/32989729/152864113-6272d5f6-f53c-43e2-b750-cdd52049b85b.png)
![image](https://user-images.githubusercontent.com/32989729/152864144-3e2d11ea-f3d7-4e78-bc05-011b0411fe62.png)

**Comment by doug-stormtree** [comment]
![IMG_6815](https://user-images.githubusercontent.com/43759986/152869629-a92202a5-46aa-45ce-ba45-d89c2d60bdce.jpeg)

**Comment by MarcusDunn** [comment]
![image](https://user-images.githubusercontent.com/51931484/152887495-ef57dd83-399f-47f0-9aab-7172f038fc98.png)
![image](https://user-images.githubusercontent.com/51931484/152887570-47732f93-03dc-460f-a81c-af5431ac0c6d.png)
![image](https://user-images.githubusercontent.com/51931484/152887594-6d5354d8-119a-4464-a0bf-c6049c8f8a34.png)

**Comment by jpark052** [comment]
![route](https://user-images.githubusercontent.com/56705512/152896602-2cde689a-8456-4efc-9bb9-3a5c8853dff0.PNG)
![groups routes panel](https://user-images.githubusercontent.com/56705512/152896603-aa53fecc-8a57-4d22-8cc2-e5c89ceaf426.PNG)
![landing page mockup](https://user-images.githubusercontent.com/56705512/152896604-761a4df3-23ab-4c55-b5df-8ae76edabe27.png)
![route modal](https://user-images.githubusercontent.com/56705512/152896605-c08f326d-d76e-4c5c-a81c-e08968d5f791.PNG)

**Comment by doug-stormtree** [comment]
![IMG_6819](https://user-images.githubusercontent.com/43759986/152903830-466cf442-574f-4a6c-8536-3f3d10ccb7b2.jpeg)

**Comment by samanthamhill** [comment]
![Untitled_Artwork](https://user-images.githubusercontent.com/74685702/152906587-c868f9a2-8416-470f-b04b-8d688c6d6066.png)
![Untitled_Artwork 2](https://user-images.githubusercontent.com/74685702/152906594-7de9a3ed-bd9c-4661-a080-92bcd9fc4483.png)
![IMG_4367](https://user-images.githubusercontent.com/74685702/152906762-3db5ecc9-75af-4bde-9c31-97299861f217.jpg)

**Comment by CobeyH** [comment]
**Cobey**
- See all rides from all groups in one place.
- Routes are displayed on a map.

**Doug**
- Passengers can create events without a specified driver.
- Rides are very event based, heavy emphasis on social elements.
- Routes are displayed in a list form for each group separately.

**Marcus**
- Rides are shown on a map separated by groups
- Chatting is based on individual rides NOT groups
- Planning is not done on group chat

**Jae**
- Thumbnail of each individual route instead of one map with all of them.
- More of a global focus instead of rides being group based.

**Samantha**
- Rides are sorted in a list for each group
- Searching is done through the map. No text search

**Takeaways**
- The main divide in our mockups is the difference between commute focus vs social focus.
- We probably want direct messaging instead of global chat

**Comment by CobeyH** [comment]
Low Fidelity Mockup Final
![image](https://user-images.githubusercontent.com/32989729/152914168-5484a33c-4e12-4263-b18f-f5d04bed8c7d.png)

**Comment by CobeyH** [comment]
At this point we have a good understanding of our MVP UI. Closing this issue
